{
  "comments": [
    {
      "key": {
        "uuid": "9a3d3df0_8e1d7a69",
        "filename": "tests/unit/benchmark/contexts/test_model.py",
        "patchSetId": 6
      },
      "lineNbr": 311,
      "author": {
        "id": 1402
      },
      "writtenOn": "2017-10-24T18:24:58Z",
      "side": 1,
      "message": "ah, so this is a bug, should not be duplicate ports.",
      "revId": "69a9321e8fe64e7c02a7fc6ef705d98aa73edf57",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9a3d3df0_4e72527d",
        "filename": "tests/unit/benchmark/contexts/test_model.py",
        "patchSetId": 6
      },
      "lineNbr": 311,
      "author": {
        "id": 1402
      },
      "writtenOn": "2017-10-25T00:55:19Z",
      "side": 1,
      "message": "or maybe not, this will be handling by Heat as an invalid config.  I don\u0027t know that we want to have _add_instance try to detect duplicate ports.  It is better to let Heat/Neutron handle it.",
      "parentUuid": "9a3d3df0_8e1d7a69",
      "revId": "69a9321e8fe64e7c02a7fc6ef705d98aa73edf57",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}