{
  "comments": [
    {
      "key": {
        "uuid": "5a3f45e8_9cf90583",
        "filename": "/COMMIT_MSG",
        "patchSetId": 2
      },
      "lineNbr": 41,
      "author": {
        "id": 7075
      },
      "writtenOn": "2018-03-26T08:21:18Z",
      "side": 1,
      "message": "A JIRA ticket is needed",
      "revId": "7e31a5c110ad8b346938229e13e4b8dbf50ea4bb",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a3f45e8_fc080993",
        "filename": "yardstick/cmd/commands/task.py",
        "patchSetId": 2
      },
      "lineNbr": 56,
      "author": {
        "id": 7075
      },
      "writtenOn": "2018-03-26T08:21:18Z",
      "side": 1,
      "message": "this should be, at least, log.error",
      "range": {
        "startLine": 56,
        "startChar": 16,
        "endLine": 56,
        "endChar": 20
      },
      "revId": "7e31a5c110ad8b346938229e13e4b8dbf50ea4bb",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a3f45e8_1c069586",
        "filename": "yardstick/cmd/commands/task.py",
        "patchSetId": 2
      },
      "lineNbr": 58,
      "author": {
        "id": 7075
      },
      "writtenOn": "2018-03-26T08:21:18Z",
      "side": 1,
      "message": "We don\u0027t need this \"else\" clause here",
      "range": {
        "startLine": 58,
        "startChar": 0,
        "endLine": 58,
        "endChar": 13
      },
      "revId": "7e31a5c110ad8b346938229e13e4b8dbf50ea4bb",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a3f45e8_7c3b5938",
        "filename": "yardstick/cmd/commands/task.py",
        "patchSetId": 2
      },
      "lineNbr": 58,
      "author": {
        "id": 1402
      },
      "writtenOn": "2018-03-26T08:30:10Z",
      "side": 1,
      "message": "we use the else to ensure that result is defined.",
      "parentUuid": "5a3f45e8_1c069586",
      "range": {
        "startLine": 58,
        "startChar": 0,
        "endLine": 58,
        "endChar": 13
      },
      "revId": "7e31a5c110ad8b346938229e13e4b8dbf50ea4bb",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a3f45e8_1c14d59e",
        "filename": "yardstick/cmd/commands/task.py",
        "patchSetId": 2
      },
      "lineNbr": 58,
      "author": {
        "id": 7075
      },
      "writtenOn": "2018-03-26T08:40:26Z",
      "side": 1,
      "message": "This is not big deal.\n\nThe result is already defined. The try/except is catching all exceptions (except Exception as e:). If we reach this line is because there is no exception.",
      "parentUuid": "5a3f45e8_7c3b5938",
      "range": {
        "startLine": 58,
        "startChar": 0,
        "endLine": 58,
        "endChar": 13
      },
      "revId": "7e31a5c110ad8b346938229e13e4b8dbf50ea4bb",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a3f45e8_5c001d67",
        "filename": "yardstick/cmd/commands/task.py",
        "patchSetId": 2
      },
      "lineNbr": 62,
      "author": {
        "id": 7075
      },
      "writtenOn": "2018-03-26T08:21:18Z",
      "side": 1,
      "message": "this should be, at least, log.error",
      "range": {
        "startLine": 62,
        "startChar": 16,
        "endLine": 62,
        "endChar": 24
      },
      "revId": "7e31a5c110ad8b346938229e13e4b8dbf50ea4bb",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a3f45e8_dc4a6dc4",
        "filename": "yardstick/cmd/commands/task.py",
        "patchSetId": 2
      },
      "lineNbr": 62,
      "author": {
        "id": 1402
      },
      "writtenOn": "2018-03-26T08:30:10Z",
      "side": 1,
      "message": "I think task failure doesn\u0027t mean an error, it just means the test failed.\n\nfailure is not error?",
      "parentUuid": "5a3f45e8_5c001d67",
      "range": {
        "startLine": 62,
        "startChar": 16,
        "endLine": 62,
        "endChar": 24
      },
      "revId": "7e31a5c110ad8b346938229e13e4b8dbf50ea4bb",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a3f45e8_5c0e5d8e",
        "filename": "yardstick/cmd/commands/task.py",
        "patchSetId": 2
      },
      "lineNbr": 62,
      "author": {
        "id": 7075
      },
      "writtenOn": "2018-03-26T08:41:40Z",
      "side": 1,
      "message": "You are right. And L56? This is another \"kind\" of failure.\n\nAnyway, the test will raise an exception.",
      "parentUuid": "5a3f45e8_dc4a6dc4",
      "range": {
        "startLine": 62,
        "startChar": 16,
        "endLine": 62,
        "endChar": 24
      },
      "revId": "7e31a5c110ad8b346938229e13e4b8dbf50ea4bb",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a3f45e8_3c039174",
        "filename": "yardstick/cmd/commands/task.py",
        "patchSetId": 2
      },
      "lineNbr": 63,
      "author": {
        "id": 7075
      },
      "writtenOn": "2018-03-26T08:21:18Z",
      "side": 1,
      "message": "IMO, we should rise an specific exception, defined in yardstick.common.exceptions",
      "range": {
        "startLine": 63,
        "startChar": 22,
        "endLine": 63,
        "endChar": 34
      },
      "revId": "7e31a5c110ad8b346938229e13e4b8dbf50ea4bb",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a3f45e8_9c274512",
        "filename": "yardstick/cmd/commands/task.py",
        "patchSetId": 2
      },
      "lineNbr": 63,
      "author": {
        "id": 5437
      },
      "writtenOn": "2018-03-26T08:55:18Z",
      "side": 1,
      "message": "Or we can print a report and don\u0027t raise any exception:\n\nFor example:\n********************************************\nopnfv_yardstick_tc001    |         PASS\nopnfv_yardstick_tc002    |         FAILED\nopnfv_yardstick_tc003    |         PASS\n********************************************",
      "parentUuid": "5a3f45e8_3c039174",
      "range": {
        "startLine": 63,
        "startChar": 22,
        "endLine": 63,
        "endChar": 34
      },
      "revId": "7e31a5c110ad8b346938229e13e4b8dbf50ea4bb",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a3f45e8_8d3d4dbe",
        "filename": "yardstick/cmd/commands/task.py",
        "patchSetId": 2
      },
      "lineNbr": 63,
      "author": {
        "id": 1402
      },
      "writtenOn": "2018-03-29T22:52:41Z",
      "side": 1,
      "message": "This is after the suite is processed?   I don\u0027t think we want a backtrace, because in this case the Test failed based on criteria.\n\nmaybe just raise SystemExit(2) or some exit code to indicate test failures.",
      "parentUuid": "5a3f45e8_9c274512",
      "range": {
        "startLine": 63,
        "startChar": 22,
        "endLine": 63,
        "endChar": 34
      },
      "revId": "7e31a5c110ad8b346938229e13e4b8dbf50ea4bb",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}